---
deployment:
  tasks:
    - export DEPLOYPATH=/home/c2569688c/public_html/lms-backend
    - /bin/cp -R . $DEPLOYPATH
    - cd $DEPLOYPATH && /usr/local/bin/php artisan cache:clear --quiet
    - cd $DEPLOYPATH && /usr/local/bin/php artisan config:clear --quiet
